### ISSUE TITLE
GUIDE TO COMPILE FOR DIFFERENT ARCHITECTURES

### ISSUE THREAD

**Issue by iAmG-r00t** [nccgroup/thetick#5]
Hello!!
 I was looking at this awesome project, but I noticed there is no guide on how to compile a binary for a different architecture, tried reading the printer compiling bit but I am still confused.

So could you kindly provide some basic requirements required to build for different architectures, like for example a router ...

Regards,

gr00t

**Comment by iAmG-r00t** [comment]
So I have checked the dep folder and noticed you have built libz, openssl and curl for the printer. Would love to understand why and also could you try to explain the makefile printer compilation area.

**Comment by MarioVilas** [comment]
Hi!

In the case of the printer, I wanted to make sure the libraries were statically linked so I didn't depend on the target actually having them installed, or having to know which version exactly. Static linking made it easier to guarantee I could just drop the binary and have it work.

For building on the current target I didn't bother with all that because that was mostly for testing anyway, this project was always meant to be used on embedded systems.

To add new platforms, basically you will edit src/Makefile to add a new "platform dependent" section of it. The variables are pretty much standard Makefile stuff except for PRECMD and POSTCMD, these are commands to execute before and after compiling - here is where the customization magic happens (for example you can do stuff like download the dependencies automatically, invoke any extra tools, pack the binary as a firmware update for your target, etc.).

I think it's a good idea to write a proper guide for this, I may do this in the future, but for now just ask me if you have any questions! :)
